debug: false
Teleportation Options:
  Require item: false
  Take item: false
  Item name: ENDER_EYE
  Charge player: false
  Charge amount: 10.0
  Anywhere item: MAGMA_CREAM
  
Portal Options:
  Charge on creation: false
  Refund on deletion: false
  Creation charge: 30.0
  Deletion return: 10.0
  Allow any player to break: false
  Emit water on creation: true
  #49 = Obsidian 45 = Brick
  Center block name: OBSIDIAN
  Outline block name: BRICKS