author: H31IX
database: false
description: Travelpad plugin for Bukkit.
main: net.h31ix.travelpad.Travelpad
name: TravelPad
startup: postworld
url: http://H31IX.NET/
version: '3.0'
softdepend: [Vault]
depend: [Unity]
api-version: 1.13
commands:
  travelpad:
    description: Use travelpad
    usage: /travelpad
    aliases: t