name: TravelPad
version: 3.1
description: Travelpad lets players create their own Physical Teleport pads (Similar to a /warp) in the world
#This plugin was originally written by H31IX however this version (Travelpads Reloaded) is maintained by Treydun
#Therefor the author tag has been changed to represent the current maintainer as spec in https://hub.spigotmc.org/javadocs/spigot/org/bukkit/plugin/PluginDescriptionFile.html
#H31IX has been moved to the authors section
author: Treydun
authors: [H31IX]
website: https://www.buildatnight.com/travelpad

main: net.h31ix.travelpad.Travelpad
api-version: 1.13
softdepend: [Vault]
depend: [Unity]
startup: postworld
#Legacy Tags
#url: http://H31IX.NET/ (Offline)
#database: false

commands:
  t:
    permission: travelpad.basic
    description: The Travelpad command
    usage: /travelpad [tp|info|list|name|delete|set]
    aliases: [travelpad,travelpads,tpads,tpadz, tpad]

permissions:
  travelpad.*:
    description: Give ALL permissions. Same as OP
    # default allowed values - true, false, op, not op or no op? Plugin page is fuzzy
    default: op
    children:
      travelpad.basic: true
      travelpad.user: true
      travelpad.admin: true
      # A value of false inherits the inverse parent permission, so -blankplugin.something?
  travelpad.basic:
    description: Permission to use basic Travelpad teleport commands.
    default: true
    children:
      travelpad.teleport: true
      travelpad.identify: true
  travelpad.user:
    description: Permission to make and remove telepads.
    default: false
    children:
      travelpad.basic: true
      travelpad.create: true
      travelpad.delete: true
      travelpad.set: true
      travelpad.prepay: true
  travelpad.admin:
    description: Permission to manage travelpads serverwide
    default: false
    children:
      travelpad.user: true
      travelpad.info.others: true
      travelpad.list.others: true
      travelpad.delete.others: true
  travelpad.reload:
    description: Permission to reload config files from disk.
    default: op
  travelpad.teleport.free:
    description: Teleport using a travelpad for free.
    default: op
  travelpad.teleport.anywhere:
    description: Dont need to be standing on a pad to teleport
    default: op